blank_issues_enabled: true
contact_links:
  - name: âœ¨ Feature Request
    url: https://github.com/statelyai/xstate/discussions/new?category=ideas
    about: Propose new features or integrations to enhance XState's functionality.
  - name: â“ Ask a Question
    url: https://github.com/statelyai/xstate/discussions/new?category=q-a
    about: Need help with XState? Ask your questions and get support from the community.
  - name: ğŸ“– Documentation
    url: https://github.com/statelyai/docs/issues/new
    about: Found a problem or have suggestions for improving our documentation? Let us know here.
  - name: ğŸ› ï¸ Stately Studio
    url: https://github.com/statelyai/studio-issues/issues/new/choose
    about: Report issues or request features specific to Stately Studio.
